name: CI/CD Pipeline - Store

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"
          terraform_wrapper: false
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t store-service:${IMAGE_TAG} .
          docker tag store-service:${IMAGE_TAG} $ECR_REGISTRY/${{ vars.store_ecr_repository_name }}:${IMAGE_TAG}
          docker push $ECR_REGISTRY/${{ vars.store_ecr_repository_name }}:${IMAGE_TAG}
          echo "IMAGE_URI=$ECR_REGISTRY/${{ vars.store_ecr_repository_name }}:${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
  
      - name: Configure AWS Credentials for Terraform
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile rv-terraform
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile rv-terraform

      - name: Get current task definition
        id: get_task_def
        run: |
          STORE_TASK_DEF_LAST=$(aws ecs describe-task-definition --task-definition="store" | jq '.taskDefinition.taskDefinitionArn')
          echo $STORE_TASK_DEF_LAST
          echo "store_task_def_last=$STORE_TASK_DEF_LAST" >> $GITHUB_OUTPUT
  
      - name: Terraform Init
        run: |
          cd ./terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd ./terraform
          terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
        id: plan
        run: |
          cd ./terraform
          terraform plan -out=tfplan

      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd ./terraform
          terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        id: tf_outputs
        shell: bash
        run: |
          STORE_TASK_DEF_NEW=$(terraform -chdir=./terraform output -raw store_task_definition_arn)
          STORE_CODEDEPLOY_APP_NAME=$(terraform -chdir=./terraform output -raw codedeploy_store_app_name)
          STORE_CODEDEPLOY_DEPLOYMENT_GROUP=$(terraform -chdir=./terraform output -raw codedeploy_store_deployment_group_name)
          echo "store_task_def_new=$STORE_TASK_DEF_NEW" >> $GITHUB_OUTPUT
          echo "store_codedeploy_app=$STORE_CODEDEPLOY_APP_NAME" >> $GITHUB_OUTPUT
          echo "store_codedeploy_deploy_group=$STORE_CODEDEPLOY_DEPLOYMENT_GROUP" >> $GITHUB_OUTPUT
          echo "Terraform outputs retrieved:"
          echo "store_task_def_new=$STORE_TASK_DEF_NEW"
          echo "store_codedeploy_app=$STORE_CODEDEPLOY_APP_NAME"
          echo "store_codedeploy_deploy_group=$STORE_CODEDEPLOY_DEPLOYMENT_GROUP"

      - name: Generate STORE AppSpec and Task Definition
        if: ${{ steps.get_task_def.outputs.STORE_TASK_DEF_LAST != steps.tf_outputs.outputs.store_task_def_new }}
        env:
          container_port: 8001
          container_name: store
        run: |
          export TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition="$container_name" | jq '.taskDefinition.taskDefinitionArn')
          cat <<EOF > store_appspec.json
          {
            "version": 1,
            "Resources": [
              {
                "TargetService": {
                  "Type": "AWS::ECS::Service",
                  "Properties": {
                    "TaskDefinition": $TASK_DEF_ARN,
                    "LoadBalancerInfo": {
                      "ContainerName": "store",
                      "ContainerPort": 8001
                    }
                  }
                }
              }
            ]
          }
          EOF
          aws ecs describe-task-definition --task-definition "store" --query taskDefinition > task-definition.json
          cat store_appspec.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: update-task-def-image
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: store
          image: ${{ steps.build.outputs.image_uri }}

      - name: ECS task deployment using CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        env:
          ACTIONS_STEP_DEBUG: true #enable step debug logging
        with:
          task-definition: task-definition.json
          service: store-service
          cluster: road-vision-cluster
          wait-for-service-stability: false
          codedeploy-appspec: store_appspec.json
          codedeploy-application: store-codedeploy-app
          codedeploy-deployment-group: store-deployment-group
